"""empty message

Revision ID: 7cf21ec9f8d3
Revises: 537a9b08ac60
Create Date: 2019-10-23 10:36:30.401623

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7cf21ec9f8d3'
down_revision = '537a9b08ac60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('state', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'state')
    # ### end Alembic commands ###
